AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  new-app

  app to start and stop ec2 instance

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MyApi1:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth: 
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: MyUsagePlan1
          Quota:
            Limit: 1000
            Period: MONTH
          Description: !Join ["", [{"Ref": "AWS::StackName"}, "-usage-plan"]]



  myEC2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Policies: AmazonEC2FullAccess
      Events:
        ANY:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ec2
            Method: ANY
            RestApiId: !Ref MyApi1
            Auth:
                ApiKeyRequired: true
        # POST:
        #   Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        #   Properties:
        #     Path: /ec2
        #     Method: post
        #     RestApiId: !Ref MyApi1
        #     Auth:
        #        ApiKeyRequired: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Ec2Api:
    Description: "API Gateway endpoint URL for Prod stage for Ec2 function"
    Value: !Sub "https://${MyApi1}.execute-api.${AWS::Region}.amazonaws.com/Prod/ec2/"




